export * from './IRenderEntities'
export * from './IUpdateEntities'
export * from './ICheckEntityCollision'
export * from './IAcceleratePaddle'
export * from './IKeepPaddleInBounds'
export * from './ILaunchBall'
export * from './IMoveBallWithPaddle'
