/* NEXT STEPS:
    - INVOKE RENDER USE CASE
    - CREATE ENTITY/DRAWABLE MANAGER (PUB/SUB)
    - RENDER BASIC BLOCK USING DRAWABLE MANAGER FROM USE CASE INVOKED FROM USE CASE
    - MOVE GAME RENDERER INVOCATION TO USE CASE
AND ONLY INVOKE USE CASE INSTEAD OF GAME RENDERER DIRECTLY
*/
